### PR TITLE
Adams pushes

### PR DESCRIPTION
**Pull request by adamhayward**
Updated dependency versions, README file, & created Sequelize models

### CODE REVIEW

**Review by alcalaluis — APPROVED** [review]

**Review by alcalaluis — APPROVED** [review]

**Review by alcalaluis — APPROVED** [review]

**Review by adamhayward — COMMENTED** [review]
most up to date

**Review by alcalaluis — APPROVED** [review]

**Review by alcalaluis — APPROVED** [review]

**Review by alcalaluis — APPROVED** [review]

**Review by alcalaluis — APPROVED** [review]

**Review by alcalaluis — APPROVED** [review]

**Review by adamhayward — COMMENTED** [review]
Approve this please

**Review by adamhayward — COMMENTED** [review]
Please approve

**Review by alcalaluis — APPROVED** [review]

**Review by adamhayward — COMMENTED** [review]
Most up to date push. 
 
See if this will merge please

**Pull request closed without merging**
